<?php
                                               
                                                    $vybavovanie_reklamacii=array();
                                                    $podiel_nakladov=array();
                                                    $index_dodavky=array();
                                                    $dni_dodania=array();
                                                    $efektivnost_predaja=array();
                                                    $objem_predanych_vyrobkov=array();
                                                    $nove_vyrobky=array();
                                                    $esady_ks=array();
                                                    $esady_eur=array();
                                                    $zakazky_datum=array();
                                                    $zakazky=array();
                                                    $zakazky_skladom=array();
                                                    $vybavovanie_reklamacii_p=array();
                                                    $podiel_nakladov_p=array();
                                                    $index_dodavky_p=array();
                                                    $dni_dodania_p=array();
                                                    $efektivnost_predaja_p=array();
                                                    $objem_predanych_vyrobkov_p=array();
                                                    $nove_vyrobky_p=array();
                                                    $esady_ks_p=array();
                                                    $esady_eur_p=array();
                                                    $zakazky_p=array();
                                                    $zakazky_skladom_p=array();
                                                    $id=array();
                                                    $num_of_actual_period=0;
                                                    while($num_of_actual_period<$count_of_periods){
                                                        $query_BU="SELECT * FROM vk WHERE YEAR(obdobie)=".$years[$num_of_actual_period]." AND MONTH(obdobie)=".$months[$num_of_actual_period]." ";
                                                        $apply_BU=mysqli_query($connect,$query_BU);
                                                        $result_BU=mysqli_fetch_array($apply_BU);
                                                        array_push($vybavovanie_reklamacii,$result_BU['doba_vybavovania_reklamacii']);
                                                        array_push($podiel_nakladov,$result_BU['podiel_nakladov_z_trzieb']);
                                                        array_push($vybavovanie_reklamacii_p,$result_BU['doba_vybavovania_reklamacii_poznamka']);
                                                        array_push($podiel_nakladov_p,$result_BU['podiel_nakladov_z_trzieb_poznamka']);
                                                        array_push($index_dodavky,$result_BU['index_perfektnej_dodavky']);
                                                        array_push($index_dodavky_p,$result_BU['index_perfektnej_dodavky_poznamka']);
                                                        array_push($dni_dodania,$result_BU['priemerne_dni_dodania']);
                                                        array_push($dni_dodania_p,$result_BU['priemerne_dni_dodania_poznamka']);
                                                        array_push($efektivnost_predaja,$result_BU['efektivnost_predaja']);
                                                        array_push($efektivnost_predaja_p,$result_BU['efektivnost_predaja_poznamka']);
                                                        array_push($objem_predanych_vyrobkov,$result_BU['sledovanie_objemu_predanych_vyrobkov']);
                                                        array_push($objem_predanych_vyrobkov_p,$result_BU['sledovanie_objemu_predanych_vyrobkov_poznamka']);
                                                        array_push($nove_vyrobky,$result_BU['nove_vyrobky']);
                                                        array_push($nove_vyrobky_p,$result_BU['nove_vyrobky_poznamka']);
                                                        array_push($esady_ks,$result_BU['mnozstvo_predanych_esad_ks']);
                                                        array_push($esady_eur,$result_BU['mnozstvo_predanych_esad_eur']);
                                                        array_push($esady_ks_p,$result_BU['mnozstvo_predanych_esad_ks_poznamka']);
                                                        array_push($esady_eur_p,$result_BU['mnozstvo_predanych_esad_eur_poznamka']);
                                                        array_push($zakazky_datum,$result_BU['zakazky_k_datum']);
                                                        array_push($zakazky,$result_BU['zakazky_k']);
                                                        array_push($zakazky_skladom,$result_BU['zakazky_k_na_sklade']);
                                                        array_push($zakazky_p,$result_BU['zakazky_k_poznamka']);
                                                        array_push($zakazky_skladom_p,$result_BU['zakazky_k_na_sklade_poznamka']);
                                                        array_push($id,$result_BU['id']);
                                                        $num_of_actual_period++;
                                                    }
                                               
                                                ?>